Snapshot before making even more changes

diff --git a/.github/workflows/dockerpush.yml b/.github/workflows/dockerpush.yml
--- a/.github/workflows/dockerpush.yml
+++ b/.github/workflows/dockerpush.yml
@@ -1,5 +1,10 @@
 name: Docker
 
+# Use this workflow to:
+# - Manually build and push an image from a branch
+# - Automatically build and push on certain pushes
+# - Automatically test new/udpated deployments
+
 on:
   push:
     # Run this workflow if */Dockerfile in main branch changed.
@@ -7,20 +12,58 @@ on:
       - main
     paths:
       - '*/Dockerfile'
-      - '.github/workflows/dockerpush.yml'
+
+  # Run when manually triggered
+  workflow_dispatch:
+    inputs:
+      # User inputs the release version, for example `1.2.3`
+      version:
+        description: 'Release version to create, for example 1.2.3'
+        required: true
+        default: "2.1.3"
 
 jobs:
   # Build and push any Dockerfile changed in this push.
-  buildandpush:
+  build-and-push:
     runs-on: ubuntu-latest
+
+    outputs:
+      fullref: ${{ steps.gettagver.outputs.fullref }}
+      shortref: ${{ steps.gettagver.outputs.shortref }}
+      sharef: ${{ steps.gettagver.outputs.sharef }}
+      tagbuilt: ${{ steps.buildimage.outputs.tagbuilt }}
+      tagpushed: ${{ steps.pushimage.outputs.tagpushed }}
 
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.after }}
-          fetch-depth: '2'
+          fetch-depth: '25'
 
-      - name: List changed Dockerfiles
+      - name: Get version details
+        # TODO: Re-ID me
+        id: gettagver
+        run: |
+          _full_ref="${{ github.ref }}"
+          _short_ref=
+          _sha_ref="${{ github.sha }}"     # TODO: Use only one?
+          _sha_short="${{ github.sha }}"
+          if [[ "${_full_ref}" == "refs/heads/"* ]]; then
+            _short_ref=${_full_ref#refs/heads/}
+          elif [[ "${_full_ref}" == "refs/tags/"* ]]; then
+            _short_ref=${_full_ref#refs/tags/}
+          else
+            echo "FAIL: Did not recognize GITHUB_REF '${_full_ref}'."
+            exit 1
+          fi
+          echo "Set fullref to '${_full_ref}'."
+          echo "Set shortref to '${_short_ref}'."
+          echo "Set sharef to '${_sha_ref}'."
+          echo "::set-output name=fullref::${_full_ref}"
+          echo "::set-output name=shortref::${_short_ref}"
+          echo "::set-output name=sharef::${_sha_ref}"
+
+      - name: List Dockerfiles to build
         # When a filename ending with /Dockerfile' has changed,
         # append it to a file named _files
         run: |
@@ -32,6 +75,8 @@ jobs:
         # Get app name from parent dir, and build each Dockerfile:
         #   <repo-owner>/<app-name>:latest
         run: |
+          _image_ver="${{ steps.gettagver.outputs.sharef }}"
+
           echo "::debug::_files is ..." && cat _files
           : > _images
           cat _files | while read -r _thisfile; do
@@ -44,6 +89,19 @@ jobs:
               echo "${_tag}" >> _images
             fi
           done
+
+
+
+          if docker build . -q \
+            --build-arg image_version="${_image_ver}" \
+            -t "${_image_tag}"; then
+            echo "Built '${_image_tag}' OK."
+          else
+            echo "FAIL: Failed to build '${_image_tag}'."
+            exit 1
+          fi
+
+
 
       - name: Push image(s) to ghcr.io
         run: |
